version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kizzo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kizzo
    ports:
      - '5432:5432'
    volumes:
      - kizzo-pg-data:/var/lib/postgresql/data

volumes:
  kizzo-pg-data:
